# Generated by Django 3.1.7 on 2025-02-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='Content',
            new_name='content',
        ),
    ]
